"use client";

import { Suspense, useEffect, useRef, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls, useGLTF, useAnimations, ContactShadows } from "@react-three/drei";
import * as THREE from "three";
import type { Pattern } from "@/lib/movements";
import { FigureStage } from "./figure-stage";
import { Mannequin3D } from "./mannequin-3d";

function hasWebGL() {
  try { const c = document.createElement("canvas"); return !!(c.getContext("webgl2") || c.getContext("webgl")); } catch { return false; }
}

// Human3D — a real rigged 3D human on the stage: orbit to view from any angle,
// with the rep playing as an animation clip. This is a SHARED asset — the same
// fit human drives both the CrossFit movement demos here and the Mars One game.
//
// The movement figures use a REAL rigged human generated by MPFB2 (MakeHuman) —
// CC0 base mesh + rig — posed through each rep by our own procedural clips
// (anatomy/blender/build_mpfb_movements.py: analytic leg solve, auto-detected
// flex signs) and exported one GLB per movement WITH its equipment. Where a
// file is missing — or WebGL isn't available — we fall back to the procedural
// mannequin / SVG FigureStage so the page never breaks.
//
// © Ankur Sinha (rig setup, movement clips, equipment). Human base mesh:
// MakeHuman / MPFB2 — CC0.

// One .glb per movement (figure + its clip), mapped by pattern. Rebuild:
//   Blender -b -P anatomy/blender/build_mpfb_human.py       (the body, once)
//   Blender -b -P anatomy/blender/build_mpfb_movements.py   (the 8 clips)
const MODEL_FOR: Record<Pattern, string> = {
  squat: "/models/squat.glb",
  hinge: "/models/deadlift.glb",
  push: "/models/press.glb",
  pull: "/models/pullup.glb",
  core: "/models/plank.glb",
  carry: "/models/walk.glb",
  cardio: "/models/run.glb",
  mobility: "/models/idle.glb",
};

// SEATED variant models — the real figure doing the rep on a chair, one per
// pattern (build_mpfb_movements.py). Shown when a seated adaptive variant is
// picked, so the 3D human actually SITS instead of standing under seated cues.
const SEATED_MODEL_FOR: Record<Pattern, string> = {
  squat: "/models/seated-squat.glb",
  hinge: "/models/seated-deadlift.glb",
  push: "/models/seated-press.glb",
  pull: "/models/seated-row.glb",
  core: "/models/seated-core.glb",
  carry: "/models/seated-carry.glb",
  cardio: "/models/seated-cardio.glb",
  mobility: "/models/seated-catcow.glb",
};

export const MODEL_CREDIT: { author: string; url: string; license: string } = {
  author: "MakeHuman / MPFB",
  url: "https://www.makehumancommunity.org",
  license: "Human base: MakeHuman/MPFB2 (CC0) · rig, clips & equipment © Ankur Sinha",
};

export function Human3D({ pattern, seated = false }: { pattern: Pattern; seated?: boolean }) {
  const [ok, setOk] = useState<boolean | null>(null); // null=checking, true=model exists, false=fallback
  const modelPath = seated ? SEATED_MODEL_FOR[pattern] : MODEL_FOR[pattern];

  // Probe for the model + WebGL before committing to a Canvas (avoids a hard crash
  // when the .glb hasn't been added yet). Re-checks when the movement changes.
  useEffect(() => {
    let alive = true;
    setOk(null);
    const gl = (() => { try { const c = document.createElement("canvas"); return !!(c.getContext("webgl2") || c.getContext("webgl")); } catch { return false; } })();
    if (!gl) { setOk(false); return; }
    fetch(modelPath, { method: "HEAD" })
      .then((r) => { if (alive) setOk(r.ok); })
      .catch(() => { if (alive) setOk(false); });
    return () => { alive = false; };
  }, [modelPath]);

  if (ok === null) {
    // Still checking for a Mixamo file — show the 3D mannequin (never the blob).
    return <Mannequin3D pattern={pattern} />;
  }
  if (ok === false) {
    // No Mixamo file: the procedural 3D mannequin is the default. Only if WebGL is
    // entirely unavailable does the SVG figure carry the demo.
    return hasWebGL() ? <Mannequin3D pattern={pattern} /> : <FigureStage pattern={pattern} />;
  }

  return (
    <div className="relative h-full min-h-[24rem] w-full overflow-hidden rounded-2xl bg-gradient-to-b from-[#0d1526] to-[#070b14]">
      {/* Cool navy studio, matching the anatomy view: neutral key + sky-blue
          rim so the figure + equipment read sculptural against the dark. */}
      <Canvas camera={{ position: [0, 0.2, 4.4], fov: 42 }} dpr={[1, 2]} shadows
        gl={{ toneMappingExposure: 1.15 }}>
        <hemisphereLight args={["#eaf2ff", "#16233c", 1.0]} />
        <directionalLight position={[3, 5, 4]} intensity={2.0} color="#fff4ea" castShadow />
        <directionalLight position={[-4, 2.5, -3]} intensity={1.0} color="#7cc0ff" />
        <Suspense fallback={null}>
          <Model path={modelPath} />
          <ContactShadows position={[0, -1, 0]} opacity={0.4} scale={6} blur={2.4} far={3} color="#020409" />
        </Suspense>
        {/* Look at the figure's mid-height (feet at y=-1, head ~y=+0.75 → center
            ~-0.15) so the whole body + its gear sits centered, not sunk low. */}
        <OrbitControls enablePan={false} target={[0, -0.15, 0]} minDistance={2.8} maxDistance={6.5}
          autoRotate autoRotateSpeed={0.5} minPolarAngle={0.35} maxPolarAngle={Math.PI / 1.85} />
      </Canvas>
      <div className="pointer-events-none absolute bottom-2 left-0 right-0 text-center text-[10px] font-medium uppercase tracking-widest text-white/40">
        drag to orbit · scroll to zoom
      </div>
      <a href={MODEL_CREDIT.url} target="_blank" rel="noreferrer"
        className="absolute bottom-1.5 right-2 text-[9px] text-white/30 hover:text-white/60">
        {MODEL_CREDIT.author}
      </a>
    </div>
  );
}

function Model({ path }: { path: string }) {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF(path);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    // Play whatever clip the file carries (one clip per movement file).
    const name = names[0];
    if (!name || !actions[name]) return;
    const action = actions[name];
    action.reset().fadeIn(0.3).play();
    action.setLoop(THREE.LoopRepeat, Infinity);
    return () => { action.fadeOut(0.2); };
  }, [actions, names]);

  // Feet at y=0 in the GLB; drop the group so the figure stands centered in view
  // (the equipment — floor/box/pull-up base — sits at the same ground plane).
  return <primitive ref={group} object={scene} scale={1} position={[0, -1, 0]} />;
}

// Preload only when a model is known to exist — guarded by the HEAD check above,
// so we don't error on a missing file. (drei preload is a no-op if never reached.)
